/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package wbs.kafka.product.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CreateProductAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6410886863602055062L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CreateProductAvroModel\",\"namespace\":\"wbs.kafka.product.avro.model\",\"fields\":[{\"name\":\"productId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"sku\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"productName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"productDescription\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"productPrice\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":10,\"scale\":2}},{\"name\":\"supplierId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"categoryId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"productStatus\",\"type\":{\"type\":\"enum\",\"name\":\"ProductStatus\",\"symbols\":[\"ACTIVE\",\"INACTIVE\",\"DISCONTINUED\"]}},{\"name\":\"failureMessages\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"default\":[]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.DecimalConversion());
  }

  private static final BinaryMessageEncoder<CreateProductAvroModel> ENCODER =
      new BinaryMessageEncoder<CreateProductAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CreateProductAvroModel> DECODER =
      new BinaryMessageDecoder<CreateProductAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CreateProductAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CreateProductAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CreateProductAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CreateProductAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CreateProductAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CreateProductAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CreateProductAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CreateProductAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String productId;
  private java.lang.String sku;
  private java.lang.String productName;
  private java.lang.String productDescription;
  private java.math.BigDecimal productPrice;
  private java.lang.String supplierId;
  private java.lang.String categoryId;
  private wbs.kafka.product.avro.model.ProductStatus productStatus;
  private java.util.List<java.lang.String> failureMessages;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CreateProductAvroModel() {}

  /**
   * All-args constructor.
   * @param productId The new value for productId
   * @param sku The new value for sku
   * @param productName The new value for productName
   * @param productDescription The new value for productDescription
   * @param productPrice The new value for productPrice
   * @param supplierId The new value for supplierId
   * @param categoryId The new value for categoryId
   * @param productStatus The new value for productStatus
   * @param failureMessages The new value for failureMessages
   */
  public CreateProductAvroModel(java.lang.String productId, java.lang.String sku, java.lang.String productName, java.lang.String productDescription, java.math.BigDecimal productPrice, java.lang.String supplierId, java.lang.String categoryId, wbs.kafka.product.avro.model.ProductStatus productStatus, java.util.List<java.lang.String> failureMessages) {
    this.productId = productId;
    this.sku = sku;
    this.productName = productName;
    this.productDescription = productDescription;
    this.productPrice = productPrice;
    this.supplierId = supplierId;
    this.categoryId = categoryId;
    this.productStatus = productStatus;
    this.failureMessages = failureMessages;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return productId;
    case 1: return sku;
    case 2: return productName;
    case 3: return productDescription;
    case 4: return productPrice;
    case 5: return supplierId;
    case 6: return categoryId;
    case 7: return productStatus;
    case 8: return failureMessages;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      new org.apache.avro.Conversions.DecimalConversion(),
      null,
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: productId = value$ != null ? value$.toString() : null; break;
    case 1: sku = value$ != null ? value$.toString() : null; break;
    case 2: productName = value$ != null ? value$.toString() : null; break;
    case 3: productDescription = value$ != null ? value$.toString() : null; break;
    case 4: productPrice = (java.math.BigDecimal)value$; break;
    case 5: supplierId = value$ != null ? value$.toString() : null; break;
    case 6: categoryId = value$ != null ? value$.toString() : null; break;
    case 7: productStatus = (wbs.kafka.product.avro.model.ProductStatus)value$; break;
    case 8: failureMessages = (java.util.List<java.lang.String>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'productId' field.
   * @return The value of the 'productId' field.
   */
  public java.lang.String getProductId() {
    return productId;
  }


  /**
   * Sets the value of the 'productId' field.
   * @param value the value to set.
   */
  public void setProductId(java.lang.String value) {
    this.productId = value;
  }

  /**
   * Gets the value of the 'sku' field.
   * @return The value of the 'sku' field.
   */
  public java.lang.String getSku() {
    return sku;
  }


  /**
   * Sets the value of the 'sku' field.
   * @param value the value to set.
   */
  public void setSku(java.lang.String value) {
    this.sku = value;
  }

  /**
   * Gets the value of the 'productName' field.
   * @return The value of the 'productName' field.
   */
  public java.lang.String getProductName() {
    return productName;
  }


  /**
   * Sets the value of the 'productName' field.
   * @param value the value to set.
   */
  public void setProductName(java.lang.String value) {
    this.productName = value;
  }

  /**
   * Gets the value of the 'productDescription' field.
   * @return The value of the 'productDescription' field.
   */
  public java.lang.String getProductDescription() {
    return productDescription;
  }


  /**
   * Sets the value of the 'productDescription' field.
   * @param value the value to set.
   */
  public void setProductDescription(java.lang.String value) {
    this.productDescription = value;
  }

  /**
   * Gets the value of the 'productPrice' field.
   * @return The value of the 'productPrice' field.
   */
  public java.math.BigDecimal getProductPrice() {
    return productPrice;
  }


  /**
   * Sets the value of the 'productPrice' field.
   * @param value the value to set.
   */
  public void setProductPrice(java.math.BigDecimal value) {
    this.productPrice = value;
  }

  /**
   * Gets the value of the 'supplierId' field.
   * @return The value of the 'supplierId' field.
   */
  public java.lang.String getSupplierId() {
    return supplierId;
  }


  /**
   * Sets the value of the 'supplierId' field.
   * @param value the value to set.
   */
  public void setSupplierId(java.lang.String value) {
    this.supplierId = value;
  }

  /**
   * Gets the value of the 'categoryId' field.
   * @return The value of the 'categoryId' field.
   */
  public java.lang.String getCategoryId() {
    return categoryId;
  }


  /**
   * Sets the value of the 'categoryId' field.
   * @param value the value to set.
   */
  public void setCategoryId(java.lang.String value) {
    this.categoryId = value;
  }

  /**
   * Gets the value of the 'productStatus' field.
   * @return The value of the 'productStatus' field.
   */
  public wbs.kafka.product.avro.model.ProductStatus getProductStatus() {
    return productStatus;
  }


  /**
   * Sets the value of the 'productStatus' field.
   * @param value the value to set.
   */
  public void setProductStatus(wbs.kafka.product.avro.model.ProductStatus value) {
    this.productStatus = value;
  }

  /**
   * Gets the value of the 'failureMessages' field.
   * @return The value of the 'failureMessages' field.
   */
  public java.util.List<java.lang.String> getFailureMessages() {
    return failureMessages;
  }


  /**
   * Sets the value of the 'failureMessages' field.
   * @param value the value to set.
   */
  public void setFailureMessages(java.util.List<java.lang.String> value) {
    this.failureMessages = value;
  }

  /**
   * Creates a new CreateProductAvroModel RecordBuilder.
   * @return A new CreateProductAvroModel RecordBuilder
   */
  public static wbs.kafka.product.avro.model.CreateProductAvroModel.Builder newBuilder() {
    return new wbs.kafka.product.avro.model.CreateProductAvroModel.Builder();
  }

  /**
   * Creates a new CreateProductAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CreateProductAvroModel RecordBuilder
   */
  public static wbs.kafka.product.avro.model.CreateProductAvroModel.Builder newBuilder(wbs.kafka.product.avro.model.CreateProductAvroModel.Builder other) {
    if (other == null) {
      return new wbs.kafka.product.avro.model.CreateProductAvroModel.Builder();
    } else {
      return new wbs.kafka.product.avro.model.CreateProductAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new CreateProductAvroModel RecordBuilder by copying an existing CreateProductAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new CreateProductAvroModel RecordBuilder
   */
  public static wbs.kafka.product.avro.model.CreateProductAvroModel.Builder newBuilder(wbs.kafka.product.avro.model.CreateProductAvroModel other) {
    if (other == null) {
      return new wbs.kafka.product.avro.model.CreateProductAvroModel.Builder();
    } else {
      return new wbs.kafka.product.avro.model.CreateProductAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for CreateProductAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CreateProductAvroModel>
    implements org.apache.avro.data.RecordBuilder<CreateProductAvroModel> {

    private java.lang.String productId;
    private java.lang.String sku;
    private java.lang.String productName;
    private java.lang.String productDescription;
    private java.math.BigDecimal productPrice;
    private java.lang.String supplierId;
    private java.lang.String categoryId;
    private wbs.kafka.product.avro.model.ProductStatus productStatus;
    private java.util.List<java.lang.String> failureMessages;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(wbs.kafka.product.avro.model.CreateProductAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.productId)) {
        this.productId = data().deepCopy(fields()[0].schema(), other.productId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.sku)) {
        this.sku = data().deepCopy(fields()[1].schema(), other.sku);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.productName)) {
        this.productName = data().deepCopy(fields()[2].schema(), other.productName);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.productDescription)) {
        this.productDescription = data().deepCopy(fields()[3].schema(), other.productDescription);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.productPrice)) {
        this.productPrice = data().deepCopy(fields()[4].schema(), other.productPrice);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.supplierId)) {
        this.supplierId = data().deepCopy(fields()[5].schema(), other.supplierId);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.categoryId)) {
        this.categoryId = data().deepCopy(fields()[6].schema(), other.categoryId);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.productStatus)) {
        this.productStatus = data().deepCopy(fields()[7].schema(), other.productStatus);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.failureMessages)) {
        this.failureMessages = data().deepCopy(fields()[8].schema(), other.failureMessages);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
    }

    /**
     * Creates a Builder by copying an existing CreateProductAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(wbs.kafka.product.avro.model.CreateProductAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.productId)) {
        this.productId = data().deepCopy(fields()[0].schema(), other.productId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sku)) {
        this.sku = data().deepCopy(fields()[1].schema(), other.sku);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.productName)) {
        this.productName = data().deepCopy(fields()[2].schema(), other.productName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.productDescription)) {
        this.productDescription = data().deepCopy(fields()[3].schema(), other.productDescription);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.productPrice)) {
        this.productPrice = data().deepCopy(fields()[4].schema(), other.productPrice);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.supplierId)) {
        this.supplierId = data().deepCopy(fields()[5].schema(), other.supplierId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.categoryId)) {
        this.categoryId = data().deepCopy(fields()[6].schema(), other.categoryId);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.productStatus)) {
        this.productStatus = data().deepCopy(fields()[7].schema(), other.productStatus);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.failureMessages)) {
        this.failureMessages = data().deepCopy(fields()[8].schema(), other.failureMessages);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'productId' field.
      * @return The value.
      */
    public java.lang.String getProductId() {
      return productId;
    }


    /**
      * Sets the value of the 'productId' field.
      * @param value The value of 'productId'.
      * @return This builder.
      */
    public wbs.kafka.product.avro.model.CreateProductAvroModel.Builder setProductId(java.lang.String value) {
      validate(fields()[0], value);
      this.productId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'productId' field has been set.
      * @return True if the 'productId' field has been set, false otherwise.
      */
    public boolean hasProductId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'productId' field.
      * @return This builder.
      */
    public wbs.kafka.product.avro.model.CreateProductAvroModel.Builder clearProductId() {
      productId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sku' field.
      * @return The value.
      */
    public java.lang.String getSku() {
      return sku;
    }


    /**
      * Sets the value of the 'sku' field.
      * @param value The value of 'sku'.
      * @return This builder.
      */
    public wbs.kafka.product.avro.model.CreateProductAvroModel.Builder setSku(java.lang.String value) {
      validate(fields()[1], value);
      this.sku = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sku' field has been set.
      * @return True if the 'sku' field has been set, false otherwise.
      */
    public boolean hasSku() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sku' field.
      * @return This builder.
      */
    public wbs.kafka.product.avro.model.CreateProductAvroModel.Builder clearSku() {
      sku = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'productName' field.
      * @return The value.
      */
    public java.lang.String getProductName() {
      return productName;
    }


    /**
      * Sets the value of the 'productName' field.
      * @param value The value of 'productName'.
      * @return This builder.
      */
    public wbs.kafka.product.avro.model.CreateProductAvroModel.Builder setProductName(java.lang.String value) {
      validate(fields()[2], value);
      this.productName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'productName' field has been set.
      * @return True if the 'productName' field has been set, false otherwise.
      */
    public boolean hasProductName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'productName' field.
      * @return This builder.
      */
    public wbs.kafka.product.avro.model.CreateProductAvroModel.Builder clearProductName() {
      productName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'productDescription' field.
      * @return The value.
      */
    public java.lang.String getProductDescription() {
      return productDescription;
    }


    /**
      * Sets the value of the 'productDescription' field.
      * @param value The value of 'productDescription'.
      * @return This builder.
      */
    public wbs.kafka.product.avro.model.CreateProductAvroModel.Builder setProductDescription(java.lang.String value) {
      validate(fields()[3], value);
      this.productDescription = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'productDescription' field has been set.
      * @return True if the 'productDescription' field has been set, false otherwise.
      */
    public boolean hasProductDescription() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'productDescription' field.
      * @return This builder.
      */
    public wbs.kafka.product.avro.model.CreateProductAvroModel.Builder clearProductDescription() {
      productDescription = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'productPrice' field.
      * @return The value.
      */
    public java.math.BigDecimal getProductPrice() {
      return productPrice;
    }


    /**
      * Sets the value of the 'productPrice' field.
      * @param value The value of 'productPrice'.
      * @return This builder.
      */
    public wbs.kafka.product.avro.model.CreateProductAvroModel.Builder setProductPrice(java.math.BigDecimal value) {
      validate(fields()[4], value);
      this.productPrice = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'productPrice' field has been set.
      * @return True if the 'productPrice' field has been set, false otherwise.
      */
    public boolean hasProductPrice() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'productPrice' field.
      * @return This builder.
      */
    public wbs.kafka.product.avro.model.CreateProductAvroModel.Builder clearProductPrice() {
      productPrice = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'supplierId' field.
      * @return The value.
      */
    public java.lang.String getSupplierId() {
      return supplierId;
    }


    /**
      * Sets the value of the 'supplierId' field.
      * @param value The value of 'supplierId'.
      * @return This builder.
      */
    public wbs.kafka.product.avro.model.CreateProductAvroModel.Builder setSupplierId(java.lang.String value) {
      validate(fields()[5], value);
      this.supplierId = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'supplierId' field has been set.
      * @return True if the 'supplierId' field has been set, false otherwise.
      */
    public boolean hasSupplierId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'supplierId' field.
      * @return This builder.
      */
    public wbs.kafka.product.avro.model.CreateProductAvroModel.Builder clearSupplierId() {
      supplierId = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'categoryId' field.
      * @return The value.
      */
    public java.lang.String getCategoryId() {
      return categoryId;
    }


    /**
      * Sets the value of the 'categoryId' field.
      * @param value The value of 'categoryId'.
      * @return This builder.
      */
    public wbs.kafka.product.avro.model.CreateProductAvroModel.Builder setCategoryId(java.lang.String value) {
      validate(fields()[6], value);
      this.categoryId = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'categoryId' field has been set.
      * @return True if the 'categoryId' field has been set, false otherwise.
      */
    public boolean hasCategoryId() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'categoryId' field.
      * @return This builder.
      */
    public wbs.kafka.product.avro.model.CreateProductAvroModel.Builder clearCategoryId() {
      categoryId = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'productStatus' field.
      * @return The value.
      */
    public wbs.kafka.product.avro.model.ProductStatus getProductStatus() {
      return productStatus;
    }


    /**
      * Sets the value of the 'productStatus' field.
      * @param value The value of 'productStatus'.
      * @return This builder.
      */
    public wbs.kafka.product.avro.model.CreateProductAvroModel.Builder setProductStatus(wbs.kafka.product.avro.model.ProductStatus value) {
      validate(fields()[7], value);
      this.productStatus = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'productStatus' field has been set.
      * @return True if the 'productStatus' field has been set, false otherwise.
      */
    public boolean hasProductStatus() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'productStatus' field.
      * @return This builder.
      */
    public wbs.kafka.product.avro.model.CreateProductAvroModel.Builder clearProductStatus() {
      productStatus = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'failureMessages' field.
      * @return The value.
      */
    public java.util.List<java.lang.String> getFailureMessages() {
      return failureMessages;
    }


    /**
      * Sets the value of the 'failureMessages' field.
      * @param value The value of 'failureMessages'.
      * @return This builder.
      */
    public wbs.kafka.product.avro.model.CreateProductAvroModel.Builder setFailureMessages(java.util.List<java.lang.String> value) {
      validate(fields()[8], value);
      this.failureMessages = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'failureMessages' field has been set.
      * @return True if the 'failureMessages' field has been set, false otherwise.
      */
    public boolean hasFailureMessages() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'failureMessages' field.
      * @return This builder.
      */
    public wbs.kafka.product.avro.model.CreateProductAvroModel.Builder clearFailureMessages() {
      failureMessages = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CreateProductAvroModel build() {
      try {
        CreateProductAvroModel record = new CreateProductAvroModel();
        record.productId = fieldSetFlags()[0] ? this.productId : (java.lang.String) defaultValue(fields()[0]);
        record.sku = fieldSetFlags()[1] ? this.sku : (java.lang.String) defaultValue(fields()[1]);
        record.productName = fieldSetFlags()[2] ? this.productName : (java.lang.String) defaultValue(fields()[2]);
        record.productDescription = fieldSetFlags()[3] ? this.productDescription : (java.lang.String) defaultValue(fields()[3]);
        record.productPrice = fieldSetFlags()[4] ? this.productPrice : (java.math.BigDecimal) defaultValue(fields()[4]);
        record.supplierId = fieldSetFlags()[5] ? this.supplierId : (java.lang.String) defaultValue(fields()[5]);
        record.categoryId = fieldSetFlags()[6] ? this.categoryId : (java.lang.String) defaultValue(fields()[6]);
        record.productStatus = fieldSetFlags()[7] ? this.productStatus : (wbs.kafka.product.avro.model.ProductStatus) defaultValue(fields()[7]);
        record.failureMessages = fieldSetFlags()[8] ? this.failureMessages : (java.util.List<java.lang.String>) defaultValue(fields()[8]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CreateProductAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<CreateProductAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CreateProductAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<CreateProductAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










