/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package wms.kafka.product.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum ProductStatus implements org.apache.avro.generic.GenericEnumSymbol<ProductStatus> {
  ACTIVE, INACTIVE, DISCONTINUED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ProductStatus\",\"namespace\":\"wbs.kafka.product.avro.model\",\"symbols\":[\"ACTIVE\",\"INACTIVE\",\"DISCONTINUED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
